[package]
name = "example_monitoring"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kuber_sim = { path = "../../kuber_sim" }
log = "0.4.21"
env_logger = "0.11.3"
